name: gym_training
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8.10
  - notebook=6.4.0
  - tk>=8.6.8
  - ffmpeg=4.2.2
  - scipy=1.6.2
  - tensorboard=2.9.1
  - pyyaml=5.4.1
  - pytorch==1.11.0
  - pip=22.1.2
  - pip:
    - numpy==1.23.1
    - matplotlib==3.5.2
    - opencv-python==4.1.2.30
    # Poligy Gradient
    - imageio==2.19.3
    - pygame==2.1.2
    - mujoco==2.1.2
    - dm-control==1.0.0
    - gym==0.25.2
    - Box2D
    # DQN
    - ale-py==0.7.5
    - pyglet==1.5.26
    - gym[atari]==0.25.2
    - autorom[accept-rom-license]==0.4.2
    - cmake==3.20.5; sys_platform != "win32"
    - wget==1.0; sys_platform != "win32"
