method: "DQN"

env:
    env_name: &env_name "ALE/Breakout-v5"
    overwrite_render: True
    record: True
    high: 255.

output:
    output_path: &output_path !join ["output/", *env_name]
    # output_path: &output_path "output/q7_dqn/"
    # model_output: "submission/model.weights"  # output weights to submission folder
    model_output: !join [*output_path, "/model_timestep-{}_{}.weights.pt"]
    log_path: !join [*output_path, "/log.txt"]
    plot_output: !join [*output_path, "/scores.png"]
    record_path: !join [*output_path, "/monitor/"]
    tensorboard_output: !join [*output_path, "/tensorboard/"]

model_training:
    # load_path: "pretrained_weights/model.weights"
    num_episodes_test: 50
    grad_clip: True
    clip_val: 10
    saving_freq: 250000
    log_freq: 50
    eval_freq: 250000
    record_freq: 250000
    soft_epsilon: 0.05

hyper_params:
    nsteps_train: 5000000
    batch_size: 32
    buffer_size: 1000000
    target_update_freq: 10000
    gamma: 0.99
    learning_freq: 4
    state_history: 4
    skip_frame: 4
    lr_begin: 0.001
    lr_end: 0.00005
    lr_nsteps: 500000
    eps_begin: 1.0
    eps_end: 0.1
    eps_nsteps: 1000000
    learning_start: 50000
